import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync('frontend/index.html', 'utf8');
const liveHtml = readFileSync('frontend/live.html', 'utf8');
const css = readFileSync('frontend/index.css', 'utf8');
const liveCss = readFileSync('frontend/live.css', 'utf8');
const js = readFileSync('frontend/index.js', 'utf8');
const liveJs = readFileSync('frontend/live.js', 'utf8');
const runScript = readFileSync('run.sh', 'utf8');

assert.match(html, /id='status-toggle-button'/, 'status toggle button should exist');
assert.match(html, /aria-controls='status-panel'/, 'status toggle should target status panel');
assert.match(html, /id='api-settings-button'/, 'game header should expose custom AI API settings');
assert.match(html, /id='export-archive-button'/, 'game header should expose life archive export');
assert.match(html, /id='retrospect-button'/, 'action area should expose manual life retrospection');
assert.match(html, /id='api-settings-panel'/, 'custom AI API settings panel should exist after login');
assert.match(html, /id='api-settings-backdrop'/, 'custom AI API settings should use a modal backdrop');
assert.match(html, /role='dialog'/, 'custom AI API settings should render as a dialog');
assert.match(html, /id='api-settings-close-button'/, 'custom AI API modal should include a close button');
assert.match(html, /id='custom-api-key'/, 'custom AI API settings should include an API key field');
assert.match(html, /id='test-api-settings-button'/, 'custom AI API settings should include a test connection button');
assert.match(html, /id='api-profile-manager'/, 'custom AI API modal should manage multiple profiles');
assert.match(html, /id='api-profile-list'/, 'custom AI API modal should list saved profiles');
assert.match(html, /id='add-api-profile-button'/, 'custom AI API modal should add profiles');
assert.match(html, /id='custom-api-name'/, 'custom AI API settings should include a profile name field');
assert.match(html, /id='activate-api-profile-button'/, 'custom AI API settings should allow activating a default profile');
assert.match(html, /id='scene-background-image'/, 'scene background should use a real image element for large data URLs');
assert.match(html, /id='calendar-type'/, 'birth form should expose calendar type');
assert.match(html, /class='quick-age-row'/, 'birth form should include start-age presets');
assert.match(html, /class='guide-card'/, 'birth form should include a beginner guide card');
assert.match(html, /class='term-grid'/, 'beginner guide should include term explanations');
assert.match(html, /id='start-age'[^>]*min='6'/, 'start age should allow gameplay from age 6');
assert.match(html, /data-age='6'/, 'birth form should include a 6-year-old quick start option');
assert.match(html, /id='element-board'/, 'chart view should show five-element distribution');
assert.match(html, /id='luck-timeline'/, 'chart view should show luck cycle timeline');
assert.match(html, /id='month-flow-board'/, 'simulation view should show current half-year flowing-month board');
assert.match(html, /id='turn-guide'/, 'simulation view should show a turn decision guide');
assert.match(html, /id='roll-stage-label'/, 'roll overlay should expose staged divination text');
assert.match(html, /本半年行动/, 'free-text action placeholder should use half-year wording');
assert.match(html, /id='codex-button'/, 'game header should expose ending codex collection');
assert.match(html, /id='codex-panel'/, 'ending codex should render as a modal panel');
assert.match(html, /id='codex-content'/, 'ending codex modal should contain collection content');
assert.match(html, /action-tray-20260608/, 'main assets should be cache-busted for the action-tray layout fix');
assert.doesNotMatch(html, /Linux\.do|login\/linuxdo/, 'Linux.do login entry should be removed');
assert.doesNotMatch(html, /id='fullscreen-button'/, 'fullscreen button should be removed');
assert.doesNotMatch(html, /start-trial-button/, 'legacy start trial button should be removed');

assert.match(css, /#app-container\s*{[^}]*height:\s*100vh/s, 'app should default to viewport height');
assert.match(css, /#app-container\s*{[^}]*max-width:\s*none/s, 'app should default to full viewport width');
assert.match(css, /#game-view\.status-collapsed\s*{[^}]*grid-template-columns:\s*48px\s+1fr/s, 'desktop collapsed status rail should keep the status panel on the left');
assert.match(css, /#game-view\.action-tray-compact\s*{[^}]*grid-template-rows:\s*auto\s+minmax\(0,\s*1fr\)\s+minmax\(10rem,\s*clamp\(10rem,\s*26vh,\s*18rem\)\)/s, 'life-simulation action tray should be height-capped on desktop');
assert.match(css, /#game-view\.action-tray-compact\s+#action-area\s*{[^}]*overflow:\s*auto/s, 'height-capped action tray should scroll internally instead of squeezing main content');
assert.match(css, /#game-view\.action-tray-compact\s+\.action-input-row\s*{[^}]*order:\s*-1/s, 'free-text action input should stay visible at the top of the compact action tray');
assert.match(css, /@media\s*\(max-width:\s*850px\)[\s\S]*#status-panel\s*{[^}]*position:\s*absolute/s, 'mobile status panel should overlay instead of consuming layout rows');
assert.match(css, /@media\s*\(max-width:\s*850px\)[\s\S]*#game-view\.status-collapsed\s+#status-panel/s, 'mobile collapsed status panel should be hidden off-canvas');
assert.match(css, /#scene-background-image\s*{[^}]*position:\s*fixed/s, 'scene background image should be fixed behind the app');
assert.match(css, /#scene-background-image\s*{[^}]*pointer-events:\s*none/s, 'scene background image must not block clicks or input');
assert.match(css, /#scene-background-image\s*{[^}]*z-index:\s*2/s, 'scene background image should visually sit above the app');
assert.match(css, /body\.has-scene-background\s+#scene-background-image\s*{[^}]*opacity:\s*0\.2/s, 'scene background should render at 0.20 opacity');
assert.match(css, /#app-container\s*{[^}]*z-index:\s*1/s, 'app content should render above the scene background layer');
assert.match(css, /#api-settings-panel\s*{[^}]*position:\s*fixed/s, 'custom AI API settings should appear as a centered modal');
assert.match(css, /#api-settings-panel\s*{[^}]*transform:\s*translate\(-50%,\s*-50%\)/s, 'custom AI API modal should be centered');
assert.match(css, /\.modal-backdrop\s*{[^}]*position:\s*fixed/s, 'custom AI API modal should dim the page behind it');
assert.match(css, /#api-profile-manager\s*{[^}]*grid-template-columns:\s*minmax\(220px,\s*0\.38fr\)\s+minmax\(0,\s*1fr\)/s, 'custom AI API modal should use profile list plus editor columns');
assert.match(css, /\.api-profile-card\s*{/, 'saved AI API profiles should render as cards');
assert.match(css, /\.guide-card\s*{/, 'beginner guide should be styled as a card');
assert.match(css, /\.term-grid\s*{/, 'term glossary should use a compact grid');
assert.match(css, /\.prelude-event-card\s*{/, 'prelude structured events should render as cards instead of raw object text');
assert.match(css, /\.turn-guide-card\s*{/, 'current turn guide should render as a decision card');
assert.match(css, /\.turn-guide-grid\s*{/, 'turn guide should summarize goal, timing, opportunities, and risks');
assert.match(css, /\.month-flow-card\s*{/, 'flowing months should render as cards');
assert.match(css, /\.system-card\s*{/, 'long-term systems should render as status cards');
assert.match(css, /\.relationship-card\s*{/, 'relationship network should render as status cards');
assert.match(css, /\.life-goal-card\s*{/, 'life goals should render as selectable cards');
assert.match(css, /\.goal-progress-card\s*{/, 'active life goal progress should render in status');
assert.match(css, /\.streak-card\s*{/, 'continuous focus streaks should render as status cards');
assert.match(css, /\.action-preview-panel\s*{/, 'action previews should render as a distinct decision panel');
assert.match(css, /\.action-preview-grid\s*{/, 'action previews should show target, goal alignment, effects, and streak prediction');
assert.match(css, /\.focus-chip\.goal-fit\s*{/, 'goal-aligned action chips should be visually marked');
assert.match(css, /\.achievement-card\s*{/, 'unlocked achievements should render as status cards');
assert.match(css, /\.milestone-card\s*{/, 'life milestones should render as status cards');
assert.match(css, /\.ending-archive\s*{/, 'ending should render as a life archive section');
assert.match(css, /\.ending-reason\s*{/, 'ending archive should show why the run ended');
assert.match(css, /\.hidden-ending-card\s*{/, 'hidden endings should render as a distinct unlock card');
assert.match(css, /\.codex-grid\s*{/, 'ending codex should render collection cards in a grid');
assert.match(css, /\.codex-card\.locked\s*{/, 'locked codex entries should show clue-only styling');
assert.match(css, /\.codex-summary\s*{/, 'ending codex should show collection progress');
assert.match(css, /\.ending-goal-card\s*{/, 'ending archive should show life goal completion');
assert.match(css, /\.history-toolbar\s*{/, 'narrative history should include filter/expand toolbar styling');
assert.match(css, /\.history-filter-chip\s*{/, 'history filters should render as accessible chips');
assert.match(css, /\.history-entry::before\s*{/, 'history entries should have type markers');
assert.match(css, /\.stage-action-hint\s*{/, 'action area should explain current life stage');
assert.match(css, /\.retrospect-button\s*{/, 'manual retrospection should have a distinct action button style');
assert.match(css, /\.divination-loader\s*{/, 'processing loader should use divination-themed UI');
assert.match(css, /#roll-overlay\.pending\s+\.dice-cup/, 'roll overlay should support a pending shake state');

assert.match(js, /statusToggleButton:\s*document\.getElementById\('status-toggle-button'\)/, 'status toggle should be wired in DOMElements');
assert.match(js, /function toggleStatusPanel\(\)/, 'status panel toggle handler should exist');
assert.match(js, /window\.matchMedia\('\(max-width: 850px\)'\)\.matches/, 'mobile should start with the status panel collapsed');
assert.match(js, /function scheduleSceneBackgroundUpdate\(\)/, 'scene background update should be scheduled after DOM rendering');
assert.match(js, /function updateSceneBackground\(\)/, 'scene background updater should exist');
assert.match(js, /function handleUnknownTimeToggle\(\)/, 'unknown time should disable the birth-time input');
assert.match(js, /function handleEditBirth\(\)/, 'chart page should allow returning to birth input');
assert.match(js, /settings\/ai/, 'frontend should call custom AI API settings endpoints');
assert.match(js, /settings\/ai\/test/, 'frontend should call custom AI API connection test endpoint');
assert.match(js, /settings\/ai\/profiles/, 'frontend should call custom AI API profile endpoints');
assert.match(js, /function submitApiSettings\(/, 'frontend should save custom AI API settings');
assert.match(js, /function testApiSettings\(/, 'frontend should test custom AI API settings');
assert.match(js, /function renderApiProfileList\(/, 'frontend should render saved AI API profile list');
assert.match(js, /function startNewApiProfile\(/, 'frontend should create a blank AI API profile draft');
assert.match(js, /function activateApiProfile\(/, 'frontend should activate a selected AI API profile');
assert.match(js, /function setApiSettingsVisible\(/, 'frontend should control custom AI API modal visibility');
assert.match(js, /apiSettingsBackdrop\.addEventListener\('click',\s*closeApiSettingsPanel\)/, 'clicking modal backdrop should close custom AI API settings');
assert.match(js, /event\.key === 'Escape'/, 'Escape should close custom AI API modal');
assert.match(js, /function renderPreludeEvent\(/, 'frontend should render prelude events as structured cards');
assert.match(js, /function joinCleanList\(/, 'frontend should clean sparse list values before joining display text');
assert.match(js, /function formatLegacyStateEffectLine\(/, 'frontend should prettify old persisted state-effect dict strings');
assert.match(js, /function renderMonthFlowBoard\(/, 'frontend should render flowing-month cards');
assert.match(js, /function renderTurnGuide\(/, 'frontend should render a decision guide for the current half-year');
assert.match(js, /showPanel\(DOMElements\.chartPanel,\s*\['chart_ready',\s*'prelude_ready'\]\.includes\(phase\)\)/, 'chart panel should not remain visible after life simulation starts');
assert.match(js, /showPanel\(DOMElements\.preludePanel,\s*phase === 'prelude_ready'\)/, 'prelude panel should not remain visible after life simulation starts');
assert.match(js, /showPanel\(DOMElements\.simulationPanel,\s*\['life_simulation',\s*'ending'\]\.includes\(phase\)\)/, 'simulation panel should own the main content after life start');
assert.match(js, /function getStreakView\(/, 'frontend should normalize continuous focus streak state');
assert.match(js, /function renderStreakStatusCard\(/, 'frontend should render continuous choice feedback in status');
assert.match(js, /function actionGuideMap\(/, 'frontend should map backend action guide previews by action');
assert.match(js, /function renderActionPreviewPanel\(/, 'frontend should render selected action preview details');
assert.match(js, /action_guides/, 'frontend should consume backend action guide previews');
assert.match(js, /action-tray-compact/, 'frontend should toggle compact action tray during life simulation');
assert.match(js, /focus_streak/, 'frontend should consume focus streak state');
assert.match(js, /focus_memory/, 'frontend should consume focus memory state');
assert.match(js, /连续选择反馈/, 'frontend should label continuous choice feedback');
assert.match(js, /function renderEndingArchive\(/, 'frontend should render enhanced ending archive');
assert.match(js, /function renderEndingCodex\(/, 'frontend should render the ending codex collection');
assert.match(js, /ending_codex/, 'frontend should consume ending codex state');
assert.match(js, /function cleanActionOptions\(/, 'frontend should clean sparse or blank action option patches before rendering chips');
assert.match(js, /function classifyHistoryItem\(/, 'frontend should classify narrative history entries');
assert.match(js, /data-history-filter/, 'frontend should render narrative history filter buttons');
assert.match(js, /HISTORY_COMPACT_LIMIT/, 'frontend should collapse long narrative histories by default');
assert.match(js, /function buildLifeArchiveMarkdown\(/, 'frontend should build a downloadable life archive');
assert.match(js, /function exportLifeArchive\(/, 'frontend should export the current life archive');
assert.match(js, /exportArchiveButton\.addEventListener\('click',\s*exportLifeArchive\)/, 'archive export button should be wired');
assert.match(js, /codexButton\.addEventListener\('click',\s*toggleCodexPanel\)/, 'ending codex button should be wired');
assert.match(js, /codexBackdrop\.addEventListener\('click',\s*closeCodexPanel\)/, 'ending codex backdrop should close the modal');
assert.match(js, /retrospectButton:\s*document\.getElementById\('retrospect-button'\)/, 'manual retrospection button should be wired in DOMElements');
assert.match(js, /function handleRetrospectLife\(\)/, 'frontend should handle manual life retrospection');
assert.match(js, /type:\s*'retrospect_life'/, 'frontend should send the retrospection action');
assert.match(js, /retrospectButton\.addEventListener\('click',\s*handleRetrospectLife\)/, 'manual retrospection button should be clickable');
assert.match(js, /state\.life_systems/, 'frontend should render long-term systems from state');
assert.match(js, /state\.relationships/, 'frontend should render relationship network from state');
assert.match(js, /state\.current_stage/, 'frontend should consume current age-stage metadata');
assert.match(js, /data-life-goal-id/, 'frontend should render selectable life goal buttons');
assert.match(js, /set_life_goal/, 'frontend should send life goal selection actions');
assert.match(js, /state\.goal_progress/, 'frontend should render active life goal progress');
assert.match(js, /state\.achievements/, 'frontend should render unlocked achievements');
assert.match(js, /state\.milestones/, 'frontend should render life milestones');
assert.match(js, /achievements_unlocked/, 'ending archive should render unlocked achievements');
assert.match(js, /ending\.hidden_ending/, 'ending archive should render hidden ending unlocks');
assert.match(js, /隐藏结局/, 'life archive export should include hidden ending labels');
assert.match(js, /结局图鉴/, 'life archive export should include ending codex progress');
assert.match(js, /joinCleanList\(month\.theme,\s*'平稳推进'\)/, 'flowing-month cards should avoid sparse-array punctuation artifacts');
assert.match(js, /function showRollPending\(/, 'frontend should show a pending roll animation immediately after submit');
assert.match(js, /Array\.isArray\(target\)\)\s*target\.splice\(Number\(key\),\s*1\)/, 'JSON Patch remove should splice arrays instead of leaving holes');
assert.match(js, /current_monthly_cycles/, 'frontend should consume current half-year monthly cycles');
assert.match(js, /life_topics/, 'chart page should render AI/deterministic life topics');
assert.match(js, /高风险领域/, 'chart page should render high-risk chart analysis fields');
assert.match(js, /luck_start_label/, 'chart page should show real luck-cycle start age independent from game start age');
assert.match(js, /age_start_label\s*&&\s*cycle\.age_end_label/, 'luck timeline should prefer age labels with months');
assert.match(js, /requestAnimationFrame\(updateSceneBackground\)/, 'scene background should update after a paint frame');
assert.match(js, /addEventListener\('load',\s*scheduleSceneBackgroundUpdate/, 'scene background should retry after image load');
assert.match(js, /sceneBackgroundImage:\s*document\.getElementById\('scene-background-image'\)/, 'scene background image should be wired in DOMElements');
assert.match(js, /DOMElements\.sceneBackgroundImage\.src\s*=\s*imageUrl/, 'scene image URL should be assigned directly to an image element');
assert.doesNotMatch(js, /fullscreenButton/, 'fullscreen button wiring should be removed');
assert.doesNotMatch(js, /startTrialButton/, 'legacy start trial wiring should be removed');

assert.match(liveHtml, /人生观测/, 'live page should use YiMingQianTu observer branding');
assert.doesNotMatch(liveHtml, /天道直播|cdn\.jsdelivr|marked|DOMPurify|pako/, 'live page should not keep old branding or CDN runtime dependencies');
assert.match(liveCss, /#live-view\.view\.active\s*{[^}]*grid-template-columns:\s*minmax\(220px,\s*18vw\)/s, 'live page should use the updated three-column observer layout');
assert.match(liveJs, /function renderTextSafe\(/, 'live page should render history without external markdown libraries');
assert.match(liveJs, /function formatLegacyStateEffectLine\(/, 'live page should prettify old persisted state-effect dict strings');
assert.doesNotMatch(liveJs, /pako|marked|DOMPurify/, 'live JS should not rely on CDN globals');

assert.match(runScript, /backend\.app\.main:app/, 'run.sh should start the YiMingQianTu FastAPI app');
assert.doesNotMatch(runScript, /ElysiaGameImmortal|\/mydata\/python/, 'run.sh should not cd into an old project path');
